### PR TITLE
yaml: add yaml.FullLoader to yaml.load_all

### PR DESCRIPTION
**Pull request by looooo**
fixes deprecation warning:
https://github.com/boltsparts/BOLTSFC/issues/5

### CODE REVIEW

**Comment by berndhahnebach** [comment]
https://github.com/boltsparts/BOLTS/commit/e5b372ee988ceb1f98615ccd6c00c7b4159fee8a

**Comment by berndhahnebach** [comment]
I get the following error:

```
Traceback (most recent call last):
  File "/home/hugo/.FreeCAD/Mod/Macros/start_bolts.FCMacro", line 1, in <module>
    import BOLTS
  File "/home/hugo/.FreeCAD/Mod/BOLTSFC/BOLTS/__init__.py", line 45, in <module>
    repo = bolttools.blt.Repository(rootpath)
  File "/home/hugo/.FreeCAD/Mod/BOLTSFC/BOLTS/bolttools/blt.py", line 252, in __init__
    raw_coll = list(yaml.load_all(open(join(path,"data",filename),"r","utf8"), Loader=yaml.FullLoader))
<class 'AttributeError'>: module 'yaml' has no attribute 'FullLoader'

```

**Comment by berndhahnebach** [comment]
furthermore I do not get the warning from issue https://github.com/boltsparts/BOLTSFC/issues/5

**Comment by looooo** [comment]
Not good. So it's depraceted and not backward compatible... Most likely you have a different y'all version.
https://stackoverflow.com/questions/55551191/module-yaml-has-no-attribute-fullloader
Then I guess it's best to revert the diff and add it once everyone uses a more up-to-date pyyaml.

**Comment by berndhahnebach** [comment]
could we check for the yaml version?

**Comment by berndhahnebach** [comment]
reverted it already.

**Comment by berndhahnebach** [comment]
https://github.com/boltsparts/BOLTS/commit/f500c11aa302b3a20f8aacde103f4bcfa3b17b3e

**Pull request closed without merging**
